/**
 * @file        RoadObj.hpp
 * @copyright   2023 Robert Bosch GmbH
 * @author      Robin Walter <robin.walter@de.bosch.com>
 * @date        12.03.2024
 * @brief       Defines structures and classes for multiple sensor and object types
 */

#pragma once
#ifndef Road_Obj_HPP
#define Road_Obj_HPP

// RoadObj includes
#include "Radar.hpp"
#include "Video.hpp"
// 1objXloc includes
#include "../object_calc/Sources/MathLibrary.hpp"
// ByteArray generation includes
#include "DataHandling.hpp"
#include "ContiDataHandling.hpp"
#include "RA6SGU_DataHandling.hpp"

namespace RoadObj {
/**
 *  @brief Used Simulator
 * @param Classe = 1
 * @param CarMaker = 2
 */
enum class Simulator {
  UNKNOWN = 0,
  Classe = 1,
  CarMaker = 2
};
/**
 *  @brief Used data transfer protocol
 * @param CAN_Bus = 1
 * @param CAN_TP = 2
 * @param Ethernet = 3
 */
enum class Data_Transfer_Protocol {
  UNKNOWN = 0,
  CAN_Bus = 1,
  CAN_TP = 2,
  Ethernet = 3
};

/**
 * @brief Contains the ego vehicle data
*/
struct Ego_Vehicle
{
  /// @brief Ego velocity in longitudinal direction (in m/s)
  double i_velocity_x;
  /// @brief Ego velocity in lateral direction (in m/s)
  double i_velocity_y;
};

class SensorHandler {
 public:
  SensorHandler() {
    i_simulator = Simulator::UNKNOWN;
    flip_coeff = 0;
    i_transfer_protocol = Data_Transfer_Protocol::UNKNOWN;
    Ego_Values.i_velocity_x = 0.0;
    Ego_Values.i_velocity_y = 0.0;
  }
  
  /**
   * @brief Calculates the necessary input values for the target calculation such as data from sensor && RCA perspective and validity flags
  */
  void calculate_all_sensor_target_data();
  /**
   * @brief Sets the values of the ego vehicle 
   * @param velocity_x Ego velocity in longitudinal direction (in m/s)
   * @param velocity_y Ego velocity in lateral direction (in m/s)
  */
  void set_ego_values(double,double);
  
  /// @brief Mounting position of the sensor in longitudinal direction in reference to the rear center axle
  Simulator i_simulator;
  /// @brief Ford specific coefficient to flip azimuth and elevation
  int flip_coeff;
  /// @brief Mounting position of the sensor in longitudinal direction in reference to the rear center axle
  Data_Transfer_Protocol i_transfer_protocol;
  /// @brief Video Front Center Sensor structure
  Video Video_FC;
  /// @brief Radar Front Center Sensor structure
  Radar Radar_FC;
  /// @brief Radar Front Left Sensor structure
  Radar Radar_FL;
  /// @brief Radar Front Right Sensor structure
  Radar Radar_FR;
  /// @brief Radar Rear Left Sensor structure
  Radar Radar_RL;
  /// @brief Radar Rear Right Sensor structure
  Radar Radar_RR;
  /// @brief Radar Rear Right Sensor structure
  Ego_Vehicle Ego_Values;
  /// @brief Contains the time needed to calculate the object and location data for all objects on all sensors
  int calculation_duration;

  /// @brief Main calculation class of the 1objXloc model which also contains the object and video calculation
  MathLibrary::TargetCalculation calculation_class;
  /// @brief Coordinatesystem which we get from the 1objXloc model with its center placed in the middle of the rear center axle
  MathLibrary::CoordinateSystem rca_cs;
  /// @brief Coordinatesystem which we get from the 1objXloc model with its center placed in the sensor position
  MathLibrary::CoordinateSystem sensor_cs;
  /// @brief Location structure of the locations generated by the 1objXloc model
  MathLibrary::LocationContour locations;

  /// @brief DataHandler for generating the byteArrays for Bosch Radars (CAN TP and Ethernet)
  DataHandler byte_array_generator;
  /// @brief DataHandler for generating the byteArrays for Conti Radars
  ContiDataHandler conti_byte_array_generator;
  /// @brief DataHandler for generating the byteArrays for RA6 SGU Radars
  RA6SGU_DataHandler ra6sgu_byte_array_generator;

 protected:
  /**
   * @brief Rotates and shifts coordinates to have both coordinate systems available (Ego: RCA and Sensor, Tgt: mid of geometry)
   * @param radar_ptr Pointer to the radar which shall be calculated
   * @param obj_id ID of the current object which shall be calculated
   * @param length Length of the target
   * @param heading_angle Relative yaw angle of the target
   * @param dist_x Relative distance in longitudinal direction to the target
   * @param dist_y Relative distance in lateral direction to the target
   * @param vel_x Velocity in longitudinal direction of the target
   * @param vel_y Velocity in longitudinal direction of the target
   * @param mount_pos_dx Mounting position of the sensor in longitudinal direction
   * @param mount_pos_dy Mounting position of the sensor in lateral direction
   * @param mount_pos_yaw Mounting position yaw angle of the sensor
   * @param ego_current_ref_point Center of the coordinate system in which the data is given in
   * @param target_current_ref_point Point on the target to which the given data is pointing
  */
  void rotate_coordinates(Sensor*,int,double , double , double , double , double , double , double , double , double , int , int);

};

}  // namespace RoadObj

#endif  // Road_Obj_HPP
