import os, sys
try:
    from Control.logging_config import logger
except ImportError:
    sys.path.append(os.path.dirname(os.path.abspath(__file__)) + r"\..\Control")
    from logging_config import logger


def generate_includes_opaque(signal_para_list):
    network_name, node_name, pdu, signal_name, signal_byte_order, signal_start_bit, signal_length, file_path = signal_para_list
    script_path = "\\".join(os.path.dirname(os.path.abspath(__file__)).split("\\")[-4:])
    signal_cin.append("// Autogenerated by -> " + script_path + r"\create_Opaque_byte_order.py")
    signal_cin.append('')
    signal_cin.append('includes')
    signal_cin.append('{')
    signal_cin.append('}')


def generate_variables_opaque(signal_para_list):
    network_name, node_name, pdu, signal_name, signal_byte_order, signal_start_bit, signal_length, file_path = signal_para_list
    signal_cin.append('')
    signal_cin.append('variables')
    signal_cin.append('{')
    signal_cin.append(f'   const BufferSize_{node_name}_{pdu}_{signal_name} = {signal_length // 8};  // Signal length in Byte')
    signal_cin.append('}')


def generate_onsysvar_opaque(signal_para_list):
    network_name, node_name, pdu, signal_name, signal_byte_order, signal_start_bit, signal_length, file_path = signal_para_list
    signal_cin.append('')
    signal_cin.append(f'on sysVar {network_name}::{pdu}::{signal_name}::sysFillData')
    signal_cin.append('{')
    signal_cin.append('   long i, txCount;')
    signal_cin.append(f'   byte sendString[BufferSize_{node_name}_{pdu}_{signal_name}];')
    signal_cin.append('   ')
    signal_cin.append('   // No action if button is released \n   if (@this==0) \n      return; \n')
    signal_cin.append(f'   txCount = @sysvar::{network_name}::{pdu}::{signal_name}::sysNoOfBytesToFill; \n')
    signal_cin.append("   // don't write over array limits \n   // limit size to prevent extremely long transfers \n")
    signal_cin.append(f'   if( txCount>BufferSize_{node_name}_{pdu}_{signal_name})')
    signal_cin.append('   {')
    signal_cin.append(f'     txCount=BufferSize_{node_name}_{pdu}_{signal_name};')
    signal_cin.append(f'     @sysvar::{network_name}::{pdu}::{signal_name}::sysNoOfBytesToFill = txCount;')
    signal_cin.append(f'     writeDbgLevel(1,"%s: Length of data string to be sent is limited to %d bytes", BufferSize_{node_name}_{pdu}_{signal_name});')
    signal_cin.append('   } \n')
    signal_cin.append("   for( i=0; i<txCount; i++ ) \n   {\n     sendString[i] = '0'+i%75;\n   } \n")
    signal_cin.append(f'   sysSetVariableData(sysvar::{network_name}::{pdu}::{signal_name}::SignalValue, sendString, txCount);')
    signal_cin.append('}')
    signal_cin.append('')
    signal_cin.append(f'on sysvar {network_name}::{pdu}::{signal_name}::SignalValue')
    signal_cin.append('{')
    signal_cin.append(f'   byte sendString[BufferSize_{node_name}_{pdu}_{signal_name}];')
    signal_cin.append('   long copiedBytes; \n\n   if (sysGetVariableArrayLength(this) > elcount( sendString)) \n   {')
    signal_cin.append(f'     writeDbgLevel(1,"%s: Data string to be sent is too large (%d), truncated to %d bytes", sysGetVariableArrayLength(this), BufferSize_{node_name}_{pdu}_{signal_name});')
    signal_cin.append('     sysGetVariableData(this, sendString, copiedBytes); \n     sysSetVariableData(this, sendString, elcount( sendString)); \n     // sysVar handler will be called again \n   }')
    signal_cin.append('   else \n   { \n     sysGetVariableData(this, sendString, copiedBytes);')
    signal_cin.append(f'     @sysvar::{network_name}::{pdu}::{signal_name}::sysNoOfBytesToSend = copiedBytes;')
    signal_cin.append('   } \n}')
    signal_cin.append('   ')
    signal_cin.append(f'on sysVar {network_name}::{pdu}::{signal_name}::sysClearData')
    signal_cin.append('{')
    signal_cin.append('   if (@this) \n')
    signal_cin.append('   { \n')
    signal_cin.append(f'     ClearReceivedData_{signal_name}(); \n')
    signal_cin.append('   } \n')
    signal_cin.append('}')


def generate_ClearReceivedData_opaque(signal_para_list):
    network_name, node_name, pdu, signal_name, signal_byte_order, signal_start_bit, signal_length, file_path = signal_para_list
    signal_cin.append('')
    signal_cin.append(f'void ClearReceivedData_{signal_name}()')
    signal_cin.append('{ \n   long size = 0; \n   byte empty_buffer[1] = 0;')
    signal_cin.append(f'   sysSetVariableData(sysvar::{network_name}::{pdu}::{signal_name}::SignalValue, empty_buffer, size);')
    signal_cin.append(f'   @{network_name}::{pdu}::{signal_name}::sysNoOfBytesToSend = 0;')
    signal_cin.append('}')


def save_cin_file(signal_para_list):
    network_name, node_name, pdu, signal_name, signal_byte_order, signal_start_bit, signal_length, file_path = signal_para_list
    try:
        file = (f'{file_path}/Opaque_Byte_Order/Opaque_{network_name}_{node_name}_{pdu}_{signal_name}.cin')
        with open(file, 'w') as outfile:
            outfile.write("\n".join(str(item) for item in signal_cin))
        logger.info(f"{file} updated successfully")
    except:
        logger.warning(f"{node_name} was NOT updated successfully", exc_info=True)


def create_Opaque_main(signal_para_list, path):
    global signal_cin
    signal_cin = ['/*@!Encoding:1252*/']
    generate_includes_opaque(signal_para_list)
    generate_variables_opaque(signal_para_list)
    generate_onsysvar_opaque(signal_para_list)
    generate_ClearReceivedData_opaque(signal_para_list)
    save_cin_file(signal_para_list)